AlessioZanga/causal-hub

src/graphs/base.rs, src/graphs/directed.rs, src/graphs/mod.rs, src/graphs/undirected.rs
=> Add `DirectedGraph` trait

.cargo/config.toml, Cargo.toml, src/data/data_matrix.rs, src/data/mod.rs, src/graphs/direction.rs, src/lib.rs, src/types.rs, tests/data/data_matrix.rs, tests/data/mod.rs, tests/graphs/algorithms/mod.rs, tests/mod.rs, tests/models/mod.rs, tests/utils/mod.rs
=> Add `DiscreteDataset` and `ContinuousDataset` structs

Cargo.toml, src/data/data_matrix.rs, src/data/data_set.rs, src/graphs/base.rs, src/graphs/structs/directed_dense_adjacency_matrix.rs, src/graphs/structs/undirected_dense_adjacency_matrix.rs
=> Add `serde` trait bounds for `BaseGraph` trait

Cargo.toml, src/stats/students_t.rs
=> Fix regression introduced by `special-fun` crate

src/graphs/algorithms/metrics/mod.rs, src/graphs/algorithms/metrics/structural_hamming_distance.rs, src/graphs/algorithms/mod.rs, src/stats/confusion_matrix.rs, src/stats/mod.rs, tests/graphs/algorithms/metrics.rs, tests/graphs/algorithms/mod.rs, tests/stats/confusion_matrix.rs, tests/stats/mod.rs
Add structural metrics as requested.
Fixes #47 
=> 47 add edges metrics

Cargo.toml, src/graphs/structs/directed_dense_adjacency_matrix.rs, src/graphs/structs/undirected_dense_adjacency_matrix.rs, src/io/dot/parser.rs, tests/io/dot.rs
Add conversion from `DOT` struct for implemented graphs.
Fixes #65 
=> Add `From<DOT>` for `Graph` and `DiGraph`

src/discovery/hill_climbing.rs, tests/discovery/hill_climbing.rs
Change `HC` implementation by adding a lifetime to scoring criterion reference.
Fixes #68 
=> Add lifetime to scoring criterion reference

.github/CONTRIBUTING.md, .github/workflows/build.yml, .github/workflows/coverage.yml, .github/workflows/docoverage.yml, .github/workflows/doctest.yml, .github/workflows/format.yml, .github/workflows/lint.yml, .github/workflows/sort.yml, Cargo.toml
Change to `dtolnay/rust-toolchain` action.
Fixes #31 
=> 31 change to dtolnayrust toolchain action

CHANGELOG.md, Cargo.toml
Prepare for release `v0.1.2`.
Fixes #70 
=> Update to `v0.1.2`

src/graphs/base.rs, src/prelude.rs, tests/graphs/base.rs
Add `L` macro as labels iterator.
Fixes #73 
=> Add `L` macro as labels iterator

src/models/mod.rs, src/models/parameter_estimator.rs, tests/models/parameter_estimator.rs
Add parameter `BayesianEstimator` following a uniform distribution.
Fixes #86 
Currently implemented for `DiscreteBN` with pseudo counts following a uniform distribution.
=> Add `BayesianEstimator`

src/graphs/structs/undirected_dense_adjacency_matrix.rs, tests/graphs/default.rs
_Fix default size in creation of complete undirected graphs._
_Add the issue reference number:_ #89 
Fixes #89 
=> Fix size of complete undirected graphs

src/discovery/conditional_independence_test.rs, src/stats/chi_squared.rs, src/stats/fisher_z.rs, src/stats/students_t.rs, tests/stats/chi_squared.rs, tests/stats/fisher_z.rs, tests/stats/students_t.rs
Conditional independece tests have been fixed. In particular, `call` function now returns `true` when not rejecting null hypothesis of independence.
Also related tests in `tests` section have been fixed.
_Add the issue reference number:_ #91 
Fixes #91 
`call` function documentation has been improved. Now it's output meaning is clearer.
=> Fix: conditional independence tests

src/models/factor.rs
Add `Into<Table>` for `Factor` by implementing `From<Factor>`.
Fixes #99 
=> Add `Into<Table>` for `Factor`

src/data/data_matrix.rs, src/data/data_set.rs, tests/data/data_matrix.rs
Add sampling methods for `DataSet` trait with related implementation on associated structs and unit tests.
Fixes #110 
=> Add sampling methods for `DataSet` trait

src/graphs/base.rs, src/graphs/structs/directed_dense_adjacency_matrix.rs, src/graphs/structs/partially_directed_dense_adjacency_matrix.rs, src/graphs/structs/undirected_dense_adjacency_matrix.rs
Remove default methods implementation for `BaseGraph`.
Fixes #108
- Bug Fix,
=> Remove default methods implementation for `BaseGraph`

src/data/count_matrix.rs, src/data/data_matrix.rs
Change `DiscreteDataMatrix` states from `usize` to `u16` to reduce memory footprint.
Fixes #112 
- Bug Fix,
=> Change `DiscreteDataMatrix` states from `usize` to `u16`

.github/CONTRIBUTING.md
Add missing test runtime dependencies instructions in the `COTRIBUTING` section.
Fixes #116 
=> Add missing test runtime dependencies instructions

.cargo/config.toml, .gitignore, Cargo.toml, extern/polars-dynamic/Cargo.toml, extern/polars-dynamic/src/lib.rs
Add `polars-dynamic` to reduce the compilation time.
Fixes #122 
- Bug Fix,
This PR allow us to remove the limit on the number of doctests running in parallel since it reduces the memory usage.
=> Add `polars-dynamic`

src/data/count_matrix.rs, src/data/data_matrix.rs, src/data/data_set.rs, src/models/bayesian_network.rs, src/stats/akaike_information_criterion.rs, src/stats/bayesian_information_criterion.rs, src/stats/chi_squared.rs, src/stats/fisher_z.rs, src/stats/log_likelihood/discrete.rs, src/stats/log_likelihood/gaussian.rs, src/stats/log_likelihood/structs.rs, src/stats/students_t.rs, tests/data/count_matrix.rs, tests/data/data_matrix.rs, tests/models/bayesian_network.rs, tests/models/mod.rs
Add `Forward` sampling for `DiscreteBN`.
Fixes #124 
- Bug Fix,
=> Add `Forward` sampling

src/discovery/hill_climbing.rs, tests/discovery/hill_climbing.rs
Fix sign comparison for strictly positivity in `HillClimbing` functor.
Fixes #128 
=> Fix sign comparison

.github/workflows/doctest.yml, src/discovery/hill_climbing.rs
Fix existing placeholders for `HillClimbing` examples.
Fixes #130 
=> Fix `HillClimbing` examples

.github/workflows/build.yml, .github/workflows/coverage.yml, .github/workflows/docoverage.yml, .github/workflows/doctest.yml, .github/workflows/format.yml, .github/workflows/lint.yml, .github/workflows/sort.yml
Reduce cache size by fixing paths.
Fixes #132 
=> Fix cache paths

src/discovery/hill_climbing.rs
Fix missing check before reverse action removal in case of prior knowledge constraints on the addition of the reversed edge.
Fixes #134 
=> Fix missing check before action removal

Cargo.toml, extern/polars-dynamic/Cargo.toml, src/data/data_matrix.rs
Polars has been updated to version 0.32.0. The arguments of its method `to_ndarray` has been updated. 
Fixes #136
=> Update polars version and fix APIs

src/stats/log_likelihood.rs
Move from `LBFGS` solver to `BFGS` solver.
Fixes #142 
=> Update to `BFGS` solver

src/stats/log_likelihood.rs
Hardening `ZINB` implementation to be numerically stable.
Fixes #144 
- Bug Fix,
=> Hardening `ZINB` implementation

src/models/bayesian_network.rs
Index out-of-bounds in `par_sample` for `CategoricalBN`.
Fixes #149 
=> Index out-of-bounds in `par_sample` for `CategoricalBN`

src/io/dot/parser.rs
Fix DOT quoting and unquoting.
Fixes #151 
=> Fix DOT quoting

src/stats/akaike_information_criterion_corrected.rs, src/stats/bayesian_information_criterion.rs, src/stats/bayesian_information_criterion_corrected.rs, src/stats/mod.rs
Add `AIC` and `BIC` variants with low sample corrections.
Fixes #153 
- Bug Fix,
=> Add `AICC` and `BICC`

Cargo.toml, benches/discovery/hill_climbing.rs, extern/polars-dynamic/Cargo.toml, src/data/count_matrix.rs, src/data/data_matrix.rs, src/data/data_set.rs, src/discovery/hill_climbing.rs, src/models/bayesian_network.rs, src/models/parameter_estimation.rs, src/models/variable_elimination.rs, src/stats/chi_squared.rs, src/stats/correlation_matrix.rs, src/stats/covariance_matrix.rs, src/stats/fisher_z.rs, src/stats/log_likelihood.rs, src/stats/students_t.rs, tests/data/count_matrix.rs, tests/data/data_matrix.rs, tests/discovery/hill_climbing.rs, tests/stats/akaike_information_criterion.rs, tests/stats/bayesian_information_criterion.rs, tests/stats/chi_squared.rs, tests/stats/fisher_z.rs, tests/stats/log_likelihood.rs, tests/stats/partial_correlation.rs, tests/stats/students_t.rs
Add traits for dataset sampling and splitting, along with their blanket implementation when possible.
Fixes #158 
- Bug Fix,
=> Add traits for dataset sampling and splitting

src/stats/log_likelihood.rs
Fix `lambda` underflow.
Fixes #160 
=> Fix `lambda` underflow
